# Generated by Django 3.2.16 on 2023-03-15 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knightswhosayni', '0004_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='license',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='knightswhosayni.license'),
            preserve_default=False,
        ),
    ]
